export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const PURCHASE_POLICY = "PURCHASE_POLICY";
export const PURCHASE_POLICY_SUCCESS = "PURCHASE_POLICY_SUCCESS";