export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const PURCHASE_POLICY = "PURCHASE_POLICY";
export const PURCHASE_POLICY_START = "PURCHASE_POLICY_START";
export const PURCHASE_POLICY_SUCCESS = "PURCHASE_POLICY_SUCCESS";
export const PURCHASE_POLICY_FAIL = "PURCHASE_POLICY_FAIL";

export const FETCH_POLICIES = "FETCH_POLICIES";
export const FETCH_POLICIES_START = "FETCH_POLICIES_START";
export const FETCH_POLICIES_SUCCESS = "FETCH_POLICIES_SUCCESS";
export const FETCH_POLICIES_FAIL = "FETCH_POLICIES_FAIL";